-- Table: public.app_user

-- DROP TABLE IF EXISTS public.app_user;

CREATE TABLE IF NOT EXISTS PUBLIC.APP_USER (
    ID BIGINT NOT NULL DEFAULT NEXTVAL('app_user_id_seq'::REGCLASS),
    NAME CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
    LASTNAME CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
    PERFIL_ID BIGINT,
    CONSTRAINT APP_USER_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_APP_USER_PERFIL_ID FOREIGN KEY (PERFIL_ID) REFERENCES PUBLIC.PERFIL (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
) TABLESPACE PG_DEFAULT;

ALTER TABLE IF EXISTS PUBLIC.APP_USER OWNER TO POSTGRES;