-- Crear secuencia para perfil
CREATE SEQUENCE IF NOT EXISTS perfil_id_seq;

-- Crear tabla perfil
CREATE TABLE IF NOT EXISTS PUBLIC.PERFIL (
    ID BIGINT NOT NULL DEFAULT NEXTVAL('perfil_id_seq'::REGCLASS),
    NAME CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
    CONSTRAINT PERFIL_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

ALTER TABLE IF EXISTS PUBLIC.PERFIL OWNER TO POSTGRES;